export enum FetchUserDetailsActionType {
    FETCH_USER_DETAILS_REQUEST = "FETCH_USER_DETAILS_REQUEST",
    FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS",
    FETCH_USER_DETAILS_FAIL = "FETCH_USER_DETAILS_FAIL"
}